### ISSUE TITLE
How to use markdown on github pages?

### ISSUE THREAD

**Issue by DaddyTrap** [ghostbody/ghostbody.github.io#4]
呃……看到师兄的pages是有markdown写的，但是以鄙人的知识只知道github pages能用html。
所以想问问师兄，这是怎么做到的……

**Comment by ghostbody** [comment]
@DaddyTrap 
You are suppose to use a markdown server locally name Jeklly. Jeklly is a simple and static blog web system using Ruby as its programming language. Also Github uses it as the building tool for git pages.

Well, you can also use pandoc to convert your markdown to html. All presentation of pages are html+css+js, markdown is just a middle level language for writing.

Reference: [using Jeklly](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)

**Comment by DaddyTrap** [comment]
@ghostbody 
It seems I have many things to learn...

Anyway....I am really grateful to you for your helps. Maybe I can close this issue?
